package constants

enum class LettersGer(val letter: Char, val value: Int, val count: Int) {
    A('a', 1, 5),
    B('b', 3, 2),
    C('c', 4, 2),
    D('d', 1, 4),
    E('e', 1, 15),
    F('f', 4, 2),
    G('g', 2, 3),
    H('h', 2, 4),
    I('i', 1, 5),
    J('j', 5, 1),
    K('k', 4, 2),
    L('l', 2, 3),
    M('m', 3, 4),
    N('n', 1, 9),
    O('o', 2, 3),
    P('p', 4, 1),
    Q('q', 10, 1),
    R('r', 1, 6),
    S('s', 1, 7),
    T('t', 1, 6),
    U('u', 1, 6),
    V('v', 5, 1),
    W('w', 3, 1),
    X('x', 8, 1),
    Y('y', 10, 1),
    Z('z', 3, 1),
    AE('ä', 5, 1),
    OE('ö', 8, 1),
    UE('ü', 5, 1),
    SZ('ß', 10, 1)
}